### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by WendellTheTechie** [thelastbaldwin/auto_share#1]
Not working for me.  I went to the URL and typed javascript: and then I copied and pasted the script in the folder auto_share.js

**Comment by WendellTheTechie** [comment]
Yeah I did all that and I am using chrome. After I hit enter it just loads
the next 48 items and that's all it does.
I'm sure it's not your script and something I'm doing wrong. I know nothing
about coding but I inspire to.

**Comment by sula70** [comment]
Hi there - having exactly the sane issue as Wendell...also tried running from console with same result - "undefined". Have double checked all of the above. Any thoughts?

**Comment by thelastbaldwin** [comment]
Hey @sula70,

The "undefined" from the console is expected. The script just executes a series of actions and doesn't return a value. In Javascript the default return value is undefined when this is the case. I'm afraid there's not enough information with this issue for me to help with. You can try cloning this repo and adding a series of debugger statements to find out why the script is failing.

**Comment by thelastbaldwin** [comment]
Not enough information. Unable to reproduce behavior.

**Comment by okaf1** [comment]
This is only working on the parties page for me, I am no longer able to share my closet. It is just scrolling to the bottom and no longer sharing. Is there any way to fix?

**Comment by thelastbaldwin** [comment]
@okaf1  How many items are in your closet? There appears to be an issue that was merged into a fork of this code that fixes an issue when there are less than 48 items in the closet. I'm also curious if there are any error messages in the console when you try to run the script.

**Comment by okaf1** [comment]
I have 78 available listings. I tried the other code and it also is just working for parties.

Oh hmm. Maybe it's Poshmark. Seems like they've blocked it? I only have a basic level of understanding of the code so I'm not sure how to troubleshoot it on my own sadly.
<img width="829" alt="Screen Shot 2020-07-21 at 10 01 09 AM" src="https://user-images.githubusercontent.com/68578479/88064352-2c98b080-cb39-11ea-8ec8-2cb5750f003c.png">

**Comment by okaf1** [comment]
I've been using this for a year in full force, so either way thank you for sharing it! It's been a great help.

**Comment by thelastbaldwin** [comment]
TBH, those errors don't look related. The script can fail silently (without a console error) if poshmark denies the share requests. They are aggressively spaced at 1/2 a second apart. You can try this fix yourself by changing the 500 in the script to 1000, which is a full second, and give that a shot.
